export const articleTexts = [
  {
    ArticleIndex: 0,
    ArticleTitle: "Zadbaj o swoją relację z ciałem (ze sobą)",
    SmallText: "Bądź dla/na siebie uważn_ i czuł_. Zapisuj swoje odczucia z ciała oraz spróbuj zrozumieć, co przez nie próbuje powiedzieć Ci Twój organizm – oraz postaraj się na nie odpowiadać. Spójrz na poniższe przykładowe komunikaty:",
    MediumText: ["Potrzebuję paliwa, by móc dalej funkcjonować","Wyczułem zagrożenie, dlatego uruchomiłem mechanizmy utrzymujące Cię w gotowości, byś był_ w stanie sprostać temu, co nadciąga","Boisz się i tak próbuje Ci to zakomunikować", "Zwracam Ci uwagę, że bierzesz za dużo na siebie. Nie dajesz już rady (choć pewnie bardzo byś chciał_).Być może czujsze też złość, ale nie chcesz jej okazać."],
    DotLineHeader: ["GŁÓD","STRES","NAPIĘCIE W KLATCE","BÓL GŁOWY"],
ForwardingButton:"Zabierz się na spacer",
  },
    {
      ArticleIndex: 1,
      ArticleTitle: "Zabierz się na spacer",
      SmallText: "Ruch to bardzo ważna część bycia człowiekiem. Jesteśmy do ruchu stworzeni! A taki spacer może być świetną chwilą w ciągu dnia na zadbanie o ciało jak i zresetowanie głowy. Spróbuj nie brać ze sobą telefonu, by jak najwięcej uwagi poświęcić na czerpanie przyjemności z ruchu oraz na bycie blisko siebie. Dodaj do tego jeszcze intencję, by podczas spaceru skupiać się na tym, za co jesteś w życiu wdzięczny, a efekt #cured gwarantowany!",
      MediumText: "https://www.youtube.com/watch?v=X462W9yc7fI",
      DotLineHeader: "FILMIK-INSPIRACJA",
  ForwardingButton:"Znajdź nową ruchową zajawkę",
    },
     {
          ArticleIndex: 2,
          ArticleTitle: "Znajdź nową ruchową zajawkę",
          SmallText: ["Nie jest ważne, jaki rodzaj ruchu przeważa w Twoim życiu – ważne, by było go dużo! By cieszyć się sprawnym ciałem na starość specjaliści podają, by zadbać chociaż o 30 minut lekkiego ruchu 5 x w tygodniu lub 20 minut bardzo intensywnego ruchu (wzmacniającego siłę lub wytrzymałość) 3 x w tygodniu. Pamiętaj, że Twój tryb życia zależy tylko od Ciebie!","lub znajdź nową ruchową zajawkę! Próbuj różnych rodzajów aktywności i wprowadzaj je w swoje codzienne życie. Jeśli brak Ci pomysłów, przejrzyj proponowane:"],
BoldText:"Eksploruj możliwości ruchowe swojego ciała ",
      ForwardingButton:"Jedz i pij",
        },
        {
        ArticleIndex: 3,
         ArticleTitle: "Jedz i pij",
         SmallText:"Jakość spożywanego jedzenia będzie odczuwalna w całym organiźmie. Podobnie z odwodnieniem, które może powodować m.in. napięcia w ciele czy bóle głowy.",
         BoldText:"Jeśli chcesz czuć się lepiej w swoim ciele:",
         ForwardingButton:"Śpij, śnij",
        },
          {
    ArticleIndex: 4,
ArticleTitle: "Śpij, śnij",
SmallText: ["Często bagatelizujemy potrzebę wysypiania się, kiedy tak naprawdę","Podczas pierwszych 4 godzin snu ciało regeneruje się, próbując nadrobić przemęczenie z poprzedniego dnia a dopiero podczas kolejnych 3–4 odżywia i zbiera dodatkową energię na kolejny dzień. Od tego, jak ten proces przebiegnie, zależy stan każdej komórki w Twoim ciele oraz to, jak będziesz się w nim czuć po obudzeniu! Problemy ze snem są również jednym z symptomów nadmiernego stresu i kryzysu psychicznego. Nie bagatelizuj ich!"],
        BoldText:"nasz kolejny dzień zaczyna się właśnie od pójścia spać!",
        MediumText:"https://open.spotify.com/episode/38EitNF4WKsNBbMCkiSd2X",
              ForwardingButton:"Oddychaj",
              DotLineHeader:"WIĘCEJ POSŁUCHAJ TU",
                },
                {
                 ArticleIndex: 5,
                ArticleTitle: "Oddychaj",
                 BoldText:"Oddech to naturalne lekarstwo ",
                 SmallText:['Gdy oddychasz, to tak jakbyś wprowadzał_ na nowo życie do swojego ciała. Oddech pomaga w samoregulacji przeżywanych emocji oraz w niwelowaniu powstałych napięć (m.in. na tle stresowym). ','Może szybko obniżyć napięcie nerwowe, uśmierzyć ból, zmniejszyć poziom lęku i poprawić Twoje samopoczucie. Oddychaj zatem świadomie!'],
               ForwardingButton:"Zatroszcz się o swój umysł",
               DropDownTitle:["Używaj całych płuc","Oddychaj, by zniwelować napięcia","Sprawdzaj w ciągu dnia,czy oddychasz","Gdy nie chcesz czuć trudnych emocji, nieświadomie wstrzymujesz oddech i nie dajesz im ujścia – co odbija się w złej pracy układu nerwowego i mózgu. Oddech może być Twoim najlepszym przyjacielem, zawsze obecnym i chętnym pomóc. Sprawdzaj w ciągu dnia, jaki jest Twój oddech i czy jest. Jeśli nie – stosuj poniższe ćwiczenie:"],
               DropDownSmallText:["Płuca z wiekiem się “zużywają”. Jeśli oddychasz tylko górną ich częścią, na starsze lata możesz nie być w stanie oddychać tak samo jakościowo. Dlatego ważne jest, by wykorzystywać całe płuca i oddychać torem przeponowym.",],
               DropDownLink:["ZOBACZ TUTAJ","TRENING JACOBSONA","BOX BREATHING"],
                }
];