export const emotionsArticleTexts = [

   { ArticleIndex: 0,
    ArticleTitle: "Poznaj świat emocji i uczuć",
    SmallText: ["Każda z emocji jest potrzebna! Może być przyjemna lub nieprzyjemna, ale nigdy nie można powiedzieć, że jest “zła” czy pozytwyna/negatywna . Warto mieć to w pamięci, bo to właśnie przekonania o emocjach ukierunkowują Cię na dany sposób radzenia sobie z nimi (pomocny lub niepomocny w danej sytaucji). Co więcej, emocje zawsze są (nigdy nie jest się emocjonalnie neutralnym), tylko czujemy je w różnych stopniach natężenia.","Emocje są uniwersalne dla wszystkich ludzi i wrodzone. Wyróżniamy 6: radość, smutek, strach, złość, zaskoczenie i wstręt. Uczucia są natomiast “bardziej złożonymi” emocjami, np. nadzieja = radość + strach. Emocje są zazwyczaj zależne od określonych sytuacji i krótkotrwałe, w przeciwieństwie do uczuć – bardziej trwałych i bez związku z określoną sytuacją. Uczuć się uczymy – nabywamy je w trakcie interakcji z ludźmi.\nJeśli to dla Ciebie nowy temat, skorzystaj z KOŁA EMOCJI I UCZUĆ (do pobrania).","Nazywamy tak stan podwyższonego poziomu pobudzenia (napięcie mięśni, szybsze bicie serca itp). Może kryć się pod nim zarówno emocja przyjemna jak i nieprzyjemna. To, jak będziemy nazywać nasze doświadczenie, wpłynie na naszą samoregulację. Aby wykorzystać potencjał tego stanu, warto zamiast ”Ale się stresuję” (które ma negatywne skojarzenia) mówić: \n–> Jestem gotow_, moje ciało jest gotowe"
    ],
    DropDownTitle: ["Zmieniaj uczucia rzekome na uczucia prawdziwe", "Prowadź dziennik emocjonalny"],
    DropDownSmallText: ["Istnieje wiele tzw. “uczuć rzekomych”, które w rzeczywistości nie są uczuciami. Są to myśli ubrane w uczucia zawierające w sobie ocenę (której nie mówimy, ale ubieramy w formę naszego “czucia”), np. czuję się... ignorowany, nieszanowana, niezrozumiany, naciskana, doceniony. Warto je wyłapywać w naszym słowniku i szukać określeń bardziej prawdziwych. Pomoże Ci to w dobrej komunikacji z innymi, ale i zmiana słownictwa wpłynie na Twoje odczuwanie emocji, np. poczucie winy wynika z oceny sytuacji, siebie, kogoś – więc nie jest uczuciem. Jeśli spróbujesz zrezygnować z oceniania, będziesz rzadziej doświadczać nieprzyjemnych emocji\n\nPoćwicz zamianę uczuć rzekomych na uczucia prawdziwe na tym FORMULARZU.","Emocje i uczucia mogą być wywołane myślą (interpetacją, oceną bądź analizą) danej sytuacji. Zawsze również łączą się z reakcją organizmu. Może to być uczucie ciepła/zimna, odczuwane napięcie/uścisk w ciele, zmiana rytmu oddechu czy bycia serca, drganie, potliwość, płacz czy zmiana głosu.\n\nPrzynajmniej raz dziennie zapisz: sytuację (co się wydarzyło + co zwróciło Twoją uwagę), towarzyszące jej myśli, odczucia w ciele oraz emocje/uczucia. Pomoże Ci to wypracować własną “mapę” stanów emocjonalnych oraz szybciej je identyfikować i nimi zarządzać. Praktyka czyni mistrza!\n\nPoćwicz zamianę uczuć rzekomych na uczucia prawdziwe na tym FORMULARZU.",
      ],
    ForwardingButton: "Wysłuchaj swoich emocj",
    BoldText: ["Każda emocja jest uczuciem, ale nie każde uczucie jest emocją","\n* UWAGA: Stres nie jest emocją!"],
}]