export const relationshipsArticleTexts = [
  {
    ArticleIndex: 0,
    ArticleTitle: "Inwestuj w relacje",
    ForwardingButton: "Schowaj telefon",
    SmallText:
      "Relacje karmią się wspólnie spędzonym czasem na nieustannym poznawaniu się i wzajemnej ciekawości (jeśli tego zabraknie, zanika bliskość). Często możesz jednak nie wiedzieć, jakie pytania zadać, by bardziej poznać bliskich czy pogłębić daną relację.\n\nPoniżej znajdziesz kilka inspiracji:",
    MediumText: [
      "Jakie było Twoje pierwsze wrażenie mojej osoby i jak zmieniło się ono z biegiem czasu?",
      "Co we mnie cenisz?",
      "Czy lubisz osobę, jaką się stajesz?",
      "Gdybym nagle stracił_ pamięć, co byś mi powiedział_ o naszej relacji?",
      "Co Cię ostatnio wzrusza,zachwyca?",
      "Co chciał_byś powiedzieć sobie sprzed kilku lat?",
      "Czy jest dla Ciebie coś ważnego, o czym chciał_byś dziś porozmawiać/opowiedzieć?",
      "Jak się dziś czujesz?",
      "Co byś zrobił_, gdybyś się już nie bał_?",
      "Jakie zachowanie drugiej osoby sprawia, że czujesz się dla niej ważny/a?",
      "Za czym tęsknisz?",
      "Za co jesteś najbardziej wdzięczny/a?",
      "Jakiej formy wsparcia potrzebujesz w trudnych chwilach?",
    ],
  },
  {
    ArticleIndex: 1,
    ArticleTitle: "Schowaj telefon",
    BoldText: "Chcesz, by Twoi rozmówcy czuli się dla Ciebie ważni? ",
    SmallText:
      "Jest jedna bardzo prosta do zastosowania, ale i bardzo skuteczna rzecz, którą możesz zrobić: gdy z kimś rozmawiasz – schowaj telefon. Badania wykazują, że sama obecność telefonu w widocznym miejscu (nawet gdy na niego nie patrzysz lub gdy masz odwróconego ekranem ku dołowi), daje rozmówcom podświadomy komunikat, że nie dajesz im swojej uwagi i że nie są dla Ciebie ważni.",
    ForwardingButton: "Praktykuj NVC",
  },
  {
    ArticleIndex: 2,
    ArticleTitle: "Praktykuj empatyczną komunikację (NVC)",
    SmallText:
      "Według podejścia NVC warto nauczyć się 3 zachowań/postaw, których brak może przeszkodzić Ci w dbaniu o relacje:",
    ForwardingButton: "Rozwiń empatię i słuchanie",
    DropDownTitle: [
      "Nie oceniaj",
      "Bierz odpowiedzialność za swoje uczucia",
      "Bądź otwart_ na nowe",
    ],
    DropDownSmallText: [
      "Funkcjonując w trybie oceny, nieustannie oceniasz innych, otoczenie, ale i przede wszystkim siebie. (Bo inni ludzie są tylko lustrem dla nas, pokazując, jak traktujemy samych siebie.) Ta krytyczność sprawia, że nie jesteś zdolny/a do przeżywania miłości – bo Twoje serce jest obite mocną skorupą nieczułej oceny. I to samo będzie przekładać się na relacje z innymi, skutkując ich zamknięciem i utratą bliskości. Pomyśl…\n\nChcesz mieć rację czy relację?\n\n–> Co może być pomocne do zmiany?Spróbuj zmienić swój tryb funkcjonowania na obserwację. Odrzuć własne analizy, interpretacje, osądy, diagnozy czy hipotezy. W komunikacji z innymi skupiaj się na tym, co odbierają Twoje zmysły – tu i teraz. Zrezygnuj z używania kwantyfikatorów wielkich: “zawsze”, “nigdy”. Dzięki temu zaczniesz operować językiem faktów, wspólnych i niepodważalnych dla wszystkich, a starając się zrozumieć zamiast krytykować, pogłębisz swoje relacje.\n\nPrzykład:Ocena: Jesteś leniwa, nigdy nie zmywasz.\nObserwacja: Widzę, że nie zmyłaś naczyń, które powiedziałaś wczoraj, że pod koniec dnia pozmywasz. Czy coś się wydarzyło?",
      "Żyjąc w przekonaniu, że za uczucia, które czujesz, są odpowiedzialni inni ludzie bądź zaistniałe sytuacje, żyjesz w ogromnej nieświadomości siebie i uzależniasz swój komfort od czynników zewnętrznych – bo albo będziesz czekać w nieskończoność dopóki ktoś z zewnątrz nie zaspokoi Twojej potrzeby, albo będziesz postrzegać innych jako “tych, z którymi jest coś nie tak”, w postawie żądania. W ten oto sposób niewątpliwie zaserwujesz innym sporą dawkę nieadekwatnego poczucia winy (co nie sprzyja dbaniu o relacje).\n\nEmocje są zawsze informacją dla Ciebie o Tobie samym\n\nMówią o Twoich potrzebach (o zaspokojeniu lub nie) oraz jedynie Ty jesteś w stanie, biorąc za to odpowiedzialność, o nie zadbać poprzez swoje działanie. Co więcej, będąc świadomym swoich emocji i kryjących się za nimi potrzeb, możesz to komunikować jako prośbę (więcej w zakładce EMOCJE). Spróbuj i doświadcz przemiany relacji!\n\nPrzykład:\n–> komunikat zrzucający odpowiedzialność: Przez nich jestem smutny/a!–> komunikat z perspektywy “Ja”:Czuję smutek w tej sytuacji, bo miał_m potrzebę informacji zwrotnej, gdy  zaproponował_m wspólne wyjście i jej nie otrzymał_m. Proszę siebie, bym zadbał_, by następnym razem to powiedzieć od razu.",
      "Prawdziwym powodem konfliktów są rozbieżne sposoby realizacji potrzeb, a nie sprzeczne potrzeby (więcej przeczytaj w zakładce EMOCJE). Warto spróbować być otwartym na znalezienie nowego, wspólnego działania, które zaspokoi Twoją potrzebę i Twojego rozmówcy. Kurczowe trzymanie się swoich schematów skutkuje poczuciem braku zrozumienia którejś ze stron, a tym samym zaburza bliskość.",
    ],
  },
  {
    ArticleIndex: 3,
    ArticleTitle: "Rozwiń swoją empatię i aktywne słuchanie",
    ForwardingButton: "Pytaj o preferowane wsparcie",
    BoldText: [
      "Potrzeba uwagi, dzielenia się,bycia usłyszanym oraz przyjęcia, to jedne z najczęściej niezaspokajanych potrzeb.",
      "*  Staraj się unikać “zabójców empatii”:",
    ],
    MediumText: [
      "1. Aktywnie słuchaj, tworząc przestrzeń do dzielenia",
      "2. Przyjmuj rozmówcę ze wszystkim,co usłyszysz",
    ],
    SmallText: [
      "Na szczęście z pomocą przychodzi empatia – sposób towarzyszenia, pełnej skupienia obecności oraz słuchania drugiej osoby, aby za jej słowami (niezależnie od treści) odnajdywać jej uczucia i stojące za nimi potrzeby. U niektórych osób te umiejętności mogą przychodzić naturalniej, niemniej niewątpliwie można się ich nauczyć– i naprawdę warto!",
      "– zadbaj o okazywanie, że go/jej słuchasz, np. przez kontakt wzrokowy– dopytuj, czy dobrze zrozumiał_ś, co czuje i jakie ma potrzeby (skorzystaj z LISTY EMOCJI I POTRZEB)",
      "– stań się go/jej ciekaw_\n– doceń jego/jej inność",
    ],
    CarouselText: [
      "„Wszyscy inni jakoś sobie radzą, tylko nie Ty…”",
      "„Nie przesadzaj, za bardzo przeżywasz”",
      "„Jak mogłeś zrobić coś tak głupiego”",
      "„Teraz to powinnaś zrobić...”",
      "„Nie martw się, wszystko będzie dobrze!”",
      "„No coś ty, przecież to nic takiego...”",
      "„A, noa mówiłam ci już o tym, że...”",
      "„To jeszcze nic! Posłuchaj co mi się przydarzyło...”",
      "„Na twoim miejscu ja bym...”",
    ],
    CarouselName: [
      "PORÓWNYWANIE",
      "ZAPRZECZANIE UCZUCIOM",
      "OCENIANIE",
      "POUCZANIE",
      "POCIESZANIE",
      "BAGATELIZOWANIE",
      "PRZERYWANIE",
      "LICYTOWANIE",
      "NIEPROSZONE RADY",
      "",
    ],
  },
  {
    ArticleIndex: 4,
    ArticleTitle: "Pytaj o preferowany rodzaj wsparcia",
    SmallText: [
      "Gdy zauważysz, że ktoś z Twojego otoczenia może potrzebować wsparcia, które chciał_byś mu/jej okazać, możesz sam_ wyjść z propozycjami pomocy:",
      "pomoc poprzez aktywne słuchanie i empatię",
      "pomoc w uspokojeniu ciała",
      "pomoc przez aktywną obecność",
      "pomoc w znalezieniu rozwiązania problemu",
      "pomoc przez zapewnienie przestrzeni",
    ],
    BoldText: [
      "Może potrzebujesz teraz... ?",
      "-> Wysłuchania",
      "-> Przytulenia",
      "-> Wspólnego działania ",
      "-> Rady ",
      "-> Samotności ",
    ],
    ForwardingButton: "Poznaj swój język miłości",
  },
  {
    ArticleIndex: 5,
    ForwardingButton: "Poznaj swoje emocje",
    ArticleTitle: "Poznaj swój język miłości",
    BoldText: [
      "Miłość jest działaniem nastawionym na dobro człowieka",
      "*  Uwaga: Miłość jest kwestią wyboru",
    ],
    SmallText: [
      "Każdy człowiek nosi potrzebę bycia kochanym i kochania, ale często nie wie, jak napełniać swój (i czyjś) “wewnętrzny zbiornik na miłość”. Według koncepcji Chapmana istnieje 5 sposobów, na jakie ludzie wyrażają i czują (subiektywnie) miłość, ale każdy zazwyczaj ma 1–2 dominujące, które najskuteczniej sprawiają, że “czuje się” kochany, ale i którymi najłatwiej mu miłość okazywać.\n\nPoznaj swój język miłości oraz naucz się rozpoznawać je u innych, a bardzo to wpłynie na rozwój Twoich relacji!",
      "W miłość wpisana jest wolność, więc nie można jej wymusić (nie zrażaj się, gdy na Twoją próbę okazania miłości ktoś nie odpowiada, nie żądaj tego). Ale – miłość jest decyzją, którą zawsze możesz podjąć, i która zawsze rozwija Cię wewnętrznie, ilekroć ją wybierasz.",
    ],
    DropDownTitle: "5 języków miłości",
    DropDownSmallText:
      "Wyrażenia afirmatywne (język słów)\n– komplementy\n– słowa wdzięczności, podziękowania\n– słowa wsparcia\n– słowa uznania i pochwały \n– ale i: uprzejmy ton \nDobry czas (język wspólnych doświadczeń i wzajemnej uwagi) \n– robienie czegoś wspólnie z pełnym zaangażowaniem \n– rozmowa (nie dyskusja) pełna wzajemnego zasłuchania (bez przerywania) i ciekawości (zadawanie pytań) nt. emocji, myśli, pragnień \n– dawanie sobie pełnej uwagi \nPodarunki (język przyjmowania i dawania rzeczy materialnych) \n– częstowanie/dzielenie się jedzeniem \n– robienie drobnych prezentów \n– kupienie wymarzonego prezentu \n– prezent z obecności \nPrzysługi (język czynów) \n– wyręczanie kogoś \n– wykonywanie prac domowych \n– spełnianie konkretnych próśb \n– ważne jest używanie języka próśb, nie żądań \nDotyk (język ciała) \n– dotyk w towarzystwie innych (daje poczucie bycia zauważonym i ważnym) \n– dotyk w trudnej sytuacji \n– ważne: rodzaj preferowanego dotyku jest u każdej osoby inny \n– ale i: mowa ciała",
  },
];
